/// Erzeugt die Berechtigungsdateien zu den Befehlen und meldet den Pfad des
/// Gradle-Teils an tauri-build.
///
/// `COMMANDS` muss zu den Befehlen in src/lib.rs passen: aus jedem Eintrag
/// entsteht ein `allow-<befehl>`/`deny-<befehl>`-Paar unter
/// permissions/autogenerated/, auf das permissions/default.toml verweist.
const COMMANDS: &[&str] = &["update_snapshot"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
